apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog-serviceaccount
  annotations:
    azure.workload.catalog/client-id: 0fcdcfa3-bb68-4eff-b081-5141e0498955
  labels:
    azure.workload.catalog/use: "true"
